default: &default
  host: db
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
development:
  <<: *default
  database: billinho_development
test:
  <<: *default
  database: billinho_test
production:
  <<: *default
  database: billinho_production
